name: 誤字、脱字、誤訳報告
description: 誤字、脱字、誤訳等を報告
body:
- type: textarea
  id: what-happened
  - attributes:
    description: sgmlファイル名またはhtmlファイル名と問題箇所を書いてください。修正案があれば、それも書いてください。
    label: 問題の詳細
  validations:
    required: true
- type: checkboxes
  id: can-be-written
  - attributes:
    description: 貢献者としてマニュアルに記載を希望しない方は記載不可としてください。
    lebel: 貢献者として記載可否
    options:
    - label: 記載可
    - label: 記載不可
- type: input
  id: notation_name
  validations:
    required: false
  - attributes:
    description: 貢献者として記載する表記名を書いてください。
    label: 貢献者
    placeholder: 株式会社ポストグレス　翻訳太郎