name: 誤字、脱字、誤訳報告
description: 特定の誤字、脱字、誤訳等を報告
body:
- type: textarea
  id: what-happened
  attributes:
    description: （分れば）sgmlファイル名またはhtmlファイル名と問題箇所を書いてください。修正案があれば、それも書いてください。
    label: 問題の詳細
- type: dropdown
  id: can-be-written
  attributes:
    description: 貢献者としてマニュアルに記載を希望しない方は記載不可としてください。[記載例](https://www.postgresql.jp/document/current/html/jpug-doc.html)
    label: 貢献者として記載可否
    options:
    - lebel: 記載（貢献者欄に書いてください）
    - label: 記載不可
    - label: 記載済みを使用
  validations:
    required: true
- type: input
  id: notation_name
  validations:
    required: false
  attributes:
    description: 貢献者として記載する表記名を書いてください。
    label: 貢献者
    placeholder: 株式会社ポストグレス　翻訳太郎