body:
- attributes:
    description: Also tell us, what did you expect to happen?
    label: What happened?
    placeholder: Tell us what you see!
    value: A bug happened!
  id: what-happened
  type: textarea
  validations:
    required: true
description: 機能リクエストの提案
name: 機能リクエスト
