name: homebrew-tap

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: github-actions-test
          homebrew-tap: noborus/homebrew-tap
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}