name: homebrew-tap

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Extract version
        id: extract-version
        # Strip a string prefix from the git tag name:
        run: |
          echo "tag-name=v0.1.4" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          download-url: https://github.com/noborus/github-actions-test/releases/download/${{ steps.extract-version.outputs.tag-name }}/github-actions-test-${{ steps.extract-version.outputs.tag-name }}.tar.gz
          formula-name: github-actions-test
          homebrew-tap: noborus/homebrew-tap
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COMMITTER_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}