name: homebrew-tap

on:
  push:
    tags:
      - v*.*.*

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: github-actions-test
          homebrew-tap: noborus/homebrew-tap
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}