name: homebrew-tap

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Extract version
        id: extract-version
        # Strip a string prefix from the git tag name:
        run: |
          echo "tag-name=v0.1.3" >> $GITHUB_OUTPUT
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          # Optional, will create tap repo fork in organization
          org: noborus
          tap: noborus/homebrew-tap
          # Formula name, required
          formula: github-actions-test
          tag: ${{ steps.extract-version.outputs.tag-name }}