name: Release build
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Install Go
      if: success()
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Set environment variables
      shell: bash
      run: |
        echo '::set-env name=GOPATH::${{ runner.workspace }}'
        echo '::add-path::${{ runner.workspace }}/bin'
    - name: Setup XGO
      run: go get github.com/crazy-max/xgo
    - name: Run dist
      run: make dist
    - name: Upload Asset to Release with a wildcard
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.zip

