name: Release build
on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Set environment variables
      shell: bash
      run: |
        echo '::set-env name=GOPATH::${{ runner.workspace }}'
        echo '::add-path::${{ runner.workspace }}/bin'
    - name: Setup XGO
      run: go get github.com/crazy-max/xgo

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run dist
      run: make dist

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url:  ${{github.event.release.upload_url}}
        asset_path: ./dist/github-actions-test_${{github.event.release.tag_name}}_${{ matrix.goos }}_${{ matrix.arch }}.zip
        asset_name: github-actions-test_${{github.event.release.tag_name}}_${{ matrix.goos }}_${{ matrix.arch }}.zip
        asset_content_type: application/zip