name: Release build
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Install Go
      if: success()
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Set environment variables
      shell: bash
      run: |
        echo "GOPATH=${{ runner.workspace }}" >> $GITHUB_ENV
        echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH
    - name: Setup XGO
      run:  go install github.com/crazy-max/xgo@latest
    - name: Run dist
      run: make dist
    - name: Upload Asset to Release with a wildcard
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.zip
    - name: update homebrew
      run: |
          bash .github/update-homebrew-tap.sh
    - name: Push formula to homebrew tap
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        git config --global user.email "noborusai@gmail.com"
        git config --global user.name "Noboru Saito"
        git clone https://github.com/noborus/homebrew-tap.git
        cd homebrew-tap
        cp ../.github/github-actions-test.rb .
        git add github-actions-test.rb
        git commit -m "Brew formula update for github-actions-test"
        git push origin main
