name: XGo
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest

  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Setup XGO
      run: go get github.com/karalabe/xgo

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run dist
      run: make dist
